workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          find . -name "pubspec.yaml" -maxdepth 3
          cd labflutter
          flutter packages pub get
      - name: Build iOS
        script: |
          cd labflutter
          flutter build ios --release --no-codesign
    artifacts:
      - labflutter/build/ios/iphoneos/Runner.app