workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd labflutter
          flutter packages pub get
      - name: Build iOS for simulator
        script: |
          cd labflutter
          flutter build ios --simulator
    artifacts:
      - labflutter/build/ios/iphonesimulator/Runner.app